### ISSUE TITLE
parser removes non-ASCII characters

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/spacyr#58] opened 2017-05-19 14:56 UTC
Did we actually fail to check this??

```r
require(spacyr)
## Loading required package: spacyr
spacy_initialize(model = "de")
## Finding a python executable with spacy installed...
## spaCy (language model: de) is installed in /usr/local/bin/python
## successfully initialized (spaCy Version: 1.8.2, language model: de)

spacy_parse("Müller will einen gut lesbaren, knappen Programmierstil fördern.")
##    doc_id sentence_id token_id           token           lemma   pos entity
## 1   text1           1        1           Mller           mller  NOUN       
## 2   text1           1        2            will            will  VERB       
## 3   text1           1        3           einen           einen   DET       
## 4   text1           1        4             gut             gut   ADJ       
## 5   text1           1        5        lesbaren        lesbaren   ADJ       
## 6   text1           1        6               ,               , PUNCT       
## 7   text1           1        7         knappen         knappen   ADJ       
## 8   text1           1        8 Programmierstil programmierstil  NOUN       
## 9   text1           1        9          frdern          frdern  VERB       
## 10  text1           1       10               .               . PUNCT  
```

**Comment by Astelix** [comment] 2017-05-19 17:30
On my computers it works with no problem (Windows and Mac).

**Comment by kbenoit** [comment] 2017-05-19 17:53
It works with Python >= 3.5, just not with 2.7.x, due to the different handling of `u'Unicode'`.

**Comment by amatsuo** [comment] 2017-05-19 19:36
The problem is fixed now. 
```
> spacy_parse("Müller will einen gut lesbaren, knappen Programmierstil fördern.")
   doc_id sentence_id token_id           token           lemma   pos   entity
1   text1           1        1          Müller          müller PROPN PERSON_B
2   text1           1        2            will            will  VERB         
3   text1           1        3           einen           einen   DET         
4   text1           1        4             gut             gut   ADJ         
5   text1           1        5        lesbaren        lesbaren   ADJ         
6   text1           1        6               ,               , PUNCT         
7   text1           1        7         knappen         knappen   ADJ         
8   text1           1        8 Programmierstil programmierstil  NOUN         
9   text1           1        9         fördern         fördern  VERB         
10  text1           1       10               .               . PUNCT         
```
The new version is a bit slower, because of the additional encoding step, but the bottleneck is not as bad as I was worried. Here is the benchmark for parsing `data_char_ukimmig2010`. 

```
Unit: milliseconds
                                   expr      min       lq     mean   median       uq      max neval
New: spacy_parse(data_char_ukimmig2010) 424.7029 436.8767 454.8798 447.6467 466.7491 553.7722   100
Old: spacy_parse(data_char_ukimmig2010) 403.9964 414.4165 428.3884 419.3952 430.1465 541.3145   100
```

**Closed** 2017-05-19 20:19 UTC
Labels: bug
